//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vial.Analyzer {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vial.Analyzer.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency or mixin target could not be found in mscorlib or any of the required assemblies..
        /// </summary>
        internal static string Description0000 {
            get {
                return ResourceManager.GetString("Description0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certain attributes cannot be used together..
        /// </summary>
        internal static string Description0001 {
            get {
                return ResourceManager.GetString("Description0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring type of mixin member must be a mixin. Declaring type of dependency member must be a dependency or a mixin..
        /// </summary>
        internal static string Description0002 {
            get {
                return ResourceManager.GetString("Description0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module with &apos;PatchAttribute&apos; is inside an assembly with an &apos;InternalsVisibleToAttribute&apos;. Sharing internal mixins may cause issues and is not recommended..
        /// </summary>
        internal static string Description0003 {
            get {
                return ResourceManager.GetString("Description0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency type should not inherit from anything other than &apos;object&apos; to avoid missing member errors. Mixin type can inherit from interfaces, but not other classes..
        /// </summary>
        internal static string Description0004 {
            get {
                return ResourceManager.GetString("Description0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly could not be found in the list of references. For the &apos;PatchAttribute&apos; argument, use &apos;null&apos; instead if this is intentional..
        /// </summary>
        internal static string Description0005 {
            get {
                return ResourceManager.GetString("Description0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call method with a &apos;BaseDependencyAttribute&apos; from a method with no &apos;MixinAttribute&apos;..
        /// </summary>
        internal static string Description0006 {
            get {
                return ResourceManager.GetString("Description0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members with &apos;MixinAttribute&apos;, &apos;DependencyAttribute&apos;, or &apos;BaseDependencyAttribute&apos; cannot be accessible outside the assembly..
        /// </summary>
        internal static string Description0007 {
            get {
                return ResourceManager.GetString("Description0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementation does not have an &apos;InjectAttribute&apos;..
        /// </summary>
        internal static string Description0008 {
            get {
                return ResourceManager.GetString("Description0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to a member that is neither injected, nor a dependency, nor a mixin..
        /// </summary>
        internal static string Description0009 {
            get {
                return ResourceManager.GetString("Description0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct references to types inside the patched assembly or one of the dependencies are not recommended. Types with &apos;DependencyAttribute&apos; should be used instead..
        /// </summary>
        internal static string Description0010 {
            get {
                return ResourceManager.GetString("Description0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring module of injected, mixin, or dependency member must have a &apos;PatchAttribute&apos;..
        /// </summary>
        internal static string Description0011 {
            get {
                return ResourceManager.GetString("Description0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base dependency&apos;s argument types must be identical to the calling method&apos;s..
        /// </summary>
        internal static string Description0012 {
            get {
                return ResourceManager.GetString("Description0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementation cannot have a &apos;NameAttribute&apos;, as renaming the interface member is impossible..
        /// </summary>
        internal static string Description0013 {
            get {
                return ResourceManager.GetString("Description0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementations should be explicit to avoid method name collisions..
        /// </summary>
        internal static string Description0014 {
            get {
                return ResourceManager.GetString("Description0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency or mixin target &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string MessageFormat0000 {
            get {
                return ResourceManager.GetString("MessageFormat0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has both &apos;{1}&apos; and &apos;{2}&apos;.
        /// </summary>
        internal static string MessageFormat0001 {
            get {
                return ResourceManager.GetString("MessageFormat0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring type of &apos;{0}&apos; does not have a &apos;MixinAttribute&apos; or a &apos;DependencyAttribute&apos;.
        /// </summary>
        internal static string MessageFormat0002 {
            get {
                return ResourceManager.GetString("MessageFormat0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly contains a module with a &apos;PatchAttribute&apos;.
        /// </summary>
        internal static string MessageFormat0003 {
            get {
                return ResourceManager.GetString("MessageFormat0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; has a &apos;DependencyAttribute&apos; or a &apos;MixinAttribute&apos; but does not inherit from &apos;System.Object&apos;, &apos;System.Enum&apos;, &apos;System.Delegate&apos;, or &apos;System.MulticastDelegate&apos;.
        /// </summary>
        internal static string MessageFormat0004 {
            get {
                return ResourceManager.GetString("MessageFormat0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly &apos;{0}&apos; could not be found.
        /// </summary>
        internal static string MessageFormat0005 {
            get {
                return ResourceManager.GetString("MessageFormat0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;{0}&apos; does not have a &apos;MixinAttribute&apos; yet it attempts to call a method with a &apos;BaseDependencyAttribute&apos;.
        /// </summary>
        internal static string MessageFormat0006 {
            get {
                return ResourceManager.GetString("MessageFormat0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; is not declared internal.
        /// </summary>
        internal static string MessageFormat0007 {
            get {
                return ResourceManager.GetString("MessageFormat0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementation &apos;{0}&apos; does not have an &apos;InjectAttribute&apos;.
        /// </summary>
        internal static string MessageFormat0008 {
            get {
                return ResourceManager.GetString("MessageFormat0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to unavailable member &apos;{0}&apos;.
        /// </summary>
        internal static string MessageFormat0009 {
            get {
                return ResourceManager.GetString("MessageFormat0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct reference to &apos;{0}&apos; from patched or dependency assembly &apos;{1}&apos;.
        /// </summary>
        internal static string MessageFormat0010 {
            get {
                return ResourceManager.GetString("MessageFormat0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring module of type &apos;{0}&apos; is not a patch.
        /// </summary>
        internal static string MessageFormat0011 {
            get {
                return ResourceManager.GetString("MessageFormat0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base dependency argument mismatch in &apos;{0}&apos;.
        /// </summary>
        internal static string MessageFormat0012 {
            get {
                return ResourceManager.GetString("MessageFormat0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementation &apos;{0}&apos; cannot have a &apos;NameAttribute&apos;.
        /// </summary>
        internal static string MessageFormat0013 {
            get {
                return ResourceManager.GetString("MessageFormat0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementation &apos;{0}&apos; from interface &apos;{1}&apos; is not explicitly defined.
        /// </summary>
        internal static string MessageFormat0014 {
            get {
                return ResourceManager.GetString("MessageFormat0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency or mixin target not found.
        /// </summary>
        internal static string Title0000 {
            get {
                return ResourceManager.GetString("Title0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible attributes.
        /// </summary>
        internal static string Title0001 {
            get {
                return ResourceManager.GetString("Title0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring type is not a mixin or dependency.
        /// </summary>
        internal static string Title0002 {
            get {
                return ResourceManager.GetString("Title0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patched module&apos;s internal types are shared.
        /// </summary>
        internal static string Title0003 {
            get {
                return ResourceManager.GetString("Title0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency or mixin type inherits from a type.
        /// </summary>
        internal static string Title0004 {
            get {
                return ResourceManager.GetString("Title0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly not found.
        /// </summary>
        internal static string Title0005 {
            get {
                return ResourceManager.GetString("Title0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot call original method.
        /// </summary>
        internal static string Title0006 {
            get {
                return ResourceManager.GetString("Title0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member is not declared internal.
        /// </summary>
        internal static string Title0007 {
            get {
                return ResourceManager.GetString("Title0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementation must be injected.
        /// </summary>
        internal static string Title0008 {
            get {
                return ResourceManager.GetString("Title0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference to unavailable member.
        /// </summary>
        internal static string Title0009 {
            get {
                return ResourceManager.GetString("Title0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct reference to a type inside the patched assembly or one of the dependencies.
        /// </summary>
        internal static string Title0010 {
            get {
                return ResourceManager.GetString("Title0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaring module is not a patch.
        /// </summary>
        internal static string Title0011 {
            get {
                return ResourceManager.GetString("Title0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base dependency argument mismatch.
        /// </summary>
        internal static string Title0012 {
            get {
                return ResourceManager.GetString("Title0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementation cannot have a &apos;NameAttribute&apos;.
        /// </summary>
        internal static string Title0013 {
            get {
                return ResourceManager.GetString("Title0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface implementations should be explicit.
        /// </summary>
        internal static string Title0014 {
            get {
                return ResourceManager.GetString("Title0014", resourceCulture);
            }
        }
    }
}
